In [2]:
file = []
line = 'id10003 id10003/na8-QEFmj44/00003.wav'
line.split()
#file.append(line.split()[1])
#file.append(line.split()[2])  # na8-QEFmj44
#print(file)

['id10003', 'id10003/na8-QEFmj44/00003.wav']

In [7]:
import torch
embedding1 = torch.ones(1, 3)
embedding2 = torch.rand(1, 3)
embedding3 = torch.matmul(embedding1, embedding2.T)
print(embedding1)
print(embedding2)
print(embedding3)

tensor([[1., 1., 1.]])
tensor([[0.7138, 0.0579, 0.4329]])
tensor([[1.2047]])
